### ISSUE TITLE
Unable to setup- fs.js error- ENOENT error

### ISSUE THREAD

**Issue by yarnball** [Paqmind/react-ultimate#102]
Hi,

Looks like an amazing project.

I'm trying to get it installed. No errors using the steps outlined, however running:

`npm run dev`

Tells me:

fs.js:808
  return binding.readdir(pathModule._makeLong(path));

Error: ENOENT: no such file or directory, scandir '/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/globalize-webpack-plugin/node_modules/cldr-data/supplemental'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at jsonFiles (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/globalize-webpack-plugin/node_modules/cldr-data/index.js:36:22)
    at supplementalPaths (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/globalize-webpack-plugin/node_modules/cldr-data/index.js:69:27)
    at Function.cldrData.entireSupplemental (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/globalize-webpack-plugin/node_modules/cldr-data/index.js:94:29)
    at module.exports.cldr (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/globalize-webpack-plugin/util.js:9:21)
    at new DevelopmentModePlugin (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/globalize-webpack-plugin/DevelopmentModePlugin.js:22:40)
    at GlobalizePlugin.apply (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/globalize-webpack-plugin/index.js:22:5)
    at Compiler.apply (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/webpack-dev-server/node_modules/webpack/node_modules/tapable/lib/Tapable.js:164:16)
    at OptionsApply.WebpackOptionsApply.process (/Users/mac1/Dev/MeMail/Front/Ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)

**Comment by ivan-kleshnin** [comment]
Hi. Looks like some Globalize problem I never encountereed. I don't use this library for a long time so I don't know how it works with newer Node, Babel, etc. Also I no longer support this project. So me advices are

1) try to reinstall Globalize
2) try to install different Globalize version
3) try to search for this problem in Globalize repo

**Comment by yarnball** [comment]
Thanks for the reply Ivan. The project looks amazing. If its no longer supported- is there a similar project you're working on now I should use instead?

To fix I've tried:
- Re-installing globalize
- Installing old version `npm install globalize@1.1.0-rc.2 cldr-data
- Searching the Globalize repo for the issue

**Comment by ivan-kleshnin** [comment]
I stopped to use React because it was not good enough for me. I don't like Flux / Redux and other funky architectures Facebook promotes. I don't like OOP. The closest thing to what I'd wanted to see as a frontend mainstream is CycleJS. 

--

If Globalize is a problem and nothing helps – you should try to drop it alltogether.
It's was added to support localized input parsing and things like that.
Nothing crucial depends on it's presence and I believe it may be removed quite easily.

**Comment by ivan-kleshnin** [comment]
https://github.com/jquery/globalize/issues/516 -- what's your OS @yarnball ?

**Comment by yarnball** [comment]
Yes I saw your cycle JS but is it a full featured admin library like react-ultimate?

I'm using OSX.

**Comment by ivan-kleshnin** [comment]
> Yes I saw your cycle JS but is it a full featured admin library like react-ultimate?

React ultimate is not a library and it has no admin. I think you meant CRUD app.
My repo contains most of it's parts: forms, multi-page, etc. 
I didn't develop the whole app again because it was a huge time investment first time.

**Comment by yarnball** [comment]
I'd be keen to help!

I can't seem to find where to download your Cycle-ultimate. The repo is just a read me file. Am I missing something obvious?

**Comment by ivan-kleshnin** [comment]
You're right, cycle-ultimate is empty. I'm talking about

https://github.com/ivan-kleshnin/cyclejs-examples

**Comment by ivan-kleshnin** [comment]
I'm going to update this repo soon.
